version: '3'

services:
  web:
    build: .
    container_name: clipnote_web
    restart: always
    volumes:
      - .:/app
      - /www/ClipNote/static:/app/static
      - /www/ClipNote/media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=ClipNote.settings
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py update_sitemap &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 --reload --timeout 120 ClipNote.wsgi:application"

volumes:
  static_volume:
  media_volume: