version: '3'

services:
  web:
    build: .
    container_name: clipnote_web
    restart: always
    volumes:
      - .:/app
      - /www/ClipNote/static:/app/static
      - /www/ClipNote/media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # 从.env文件中读取的环境变量
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py update_sitemap &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 --reload --timeout 120 ClipNote.wsgi:application"

volumes:
  static_volume:
  media_volume: