# Generated by Django 5.1.7 on 2025-07-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='标记是否由AI生成描述', verbose_name='AI生成内容'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='generated_keywords',
            field=models.TextField(blank=True, default='[]', help_text='JSON格式存储生成内容的关键词', verbose_name='生成内容关键词'),
        ),
        migrations.CreateModel(
            name='ContentKeywordMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='关键词')),
                ('content_type', models.CharField(choices=[('what_is', 'What is'), ('tutorial', 'Tutorial'), ('mistakes', 'Common Mistakes'), ('tips', 'Tips for Better Results'), ('muscles', 'Muscles Worked'), ('other', 'Other')], max_length=50, verbose_name='内容类型')),
                ('relevance_score', models.FloatField(default=1.0, help_text='0.0-1.0之间的相关性评分', verbose_name='相关性评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_mappings', to='fitness.exercise', verbose_name='健身动作')),
            ],
            options={
                'verbose_name': '内容关键词映射',
                'verbose_name_plural': '内容关键词映射管理',
                'unique_together': {('exercise', 'keyword', 'content_type')},
            },
        ),
    ]
