# Generated by Django 5.2.2 on 2025-07-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_exercise_ai_generated_exercise_generated_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, help_text='图片的网络链接地址', verbose_name='动作图片URL'),
        ),
    ]
