# Generated by Django 5.1.7 on 2025-04-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.TextField(blank=True, default='[]', verbose_name='预览图'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, default='[]', verbose_name='关键词'),
        ),
    ]
