# Generated by Django 5.1.7 on 2025-05-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_article_images_article_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL别名'),
        ),
    ]
